/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.nhom2;

import com.nhom2.View.Login;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        new Login().setVisible(true);
    }
}
