version: "3.9"

services:
  mssql:
    image: mcr.microsoft.com/mssql/server
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: root:ROOT
    ports:
      - 1433:1433